#!/usr/bin/env bash
# HealthDM — one-shot production setup.
#
# Generates nginx.conf, .env, and docker-compose.yml inline (single-file installer — curl only this script).
# The ONLY thing downloaded from the internet is the Docker image archive (unless you use a local path).
#
# Usage:
#   bash healthdm-prod-setup.sh --url <github-release-url>
#   bash healthdm-prod-setup.sh /path/to/healthdm-prod-v1.0.0.tar.gz
#
# Requires: docker, docker compose, curl, gunzip (gzip), openssl
set -euo pipefail

# ─── RELEASE URL — update this line when publishing a new release ────────────
RELEASE_TGZ_URL="${RELEASE_TGZ_URL:-}"
# ─────────────────────────────────────────────────────────────────────────────

HEALTHDM_IMAGE_TAG="${HEALTHDM_IMAGE_TAG:-}"
INSTALL_DIR="${INSTALL_DIR:-healthdm}"
DOWNLOAD=1
TAR_PATH=""
FORCE_ENV=0

# ─── Help ─────────────────────────────────────────────────────────────────────

usage() {
  cat <<'EOF'
HealthDM Production Setup

Generates nginx, .env, and docker-compose.yml inline; downloads only the Docker image archive.

Requires: only this script (plus Docker, curl when using --url, openssl, gunzip).

Usage:
  bash healthdm-prod-setup.sh [OPTIONS] [PATH_TO_TAR_GZ]

Options:
  --url URL        GitHub Release download URL for healthdm-prod-<tag>.tar.gz
  --tag TAG        Image tag baked into the tarball (auto-detected from filename if omitted)
  --dir DIR        Installation directory (default: ./healthdm)
  --no-download    Skip download; use existing archive (pass path or --tar)
  --tar PATH       Path to a local archive (implies --no-download)
  --force-env      Regenerate .env even if it already exists
  -h, --help       Show this help

Environment variables (alternative to flags):
  RELEASE_TGZ_URL       Full download URL
  HEALTHDM_IMAGE_TAG    Image tag
  INSTALL_DIR           Installation directory

Examples:
  # First install from GitHub release:
  bash healthdm-prod-setup.sh --url https://github.com/org/repo/releases/download/v1.0.0/healthdm-prod-v1.0.0.tar.gz

  # Use a local archive:
  bash healthdm-prod-setup.sh ~/Downloads/healthdm-prod-v1.0.0.tar.gz

  # Upgrade to a new release (keeps existing .env and Postgres data):
  bash healthdm-prod-setup.sh --url <new-url> --dir ./healthdm
EOF
}

# ─── Argument parsing ─────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url)
      RELEASE_TGZ_URL="${2:?--url requires a URL}"
      shift 2
      ;;
    --tag)
      HEALTHDM_IMAGE_TAG="${2:?--tag requires a value}"
      shift 2
      ;;
    --dir)
      INSTALL_DIR="${2:?--dir requires a path}"
      shift 2
      ;;
    --no-download)
      DOWNLOAD=0
      shift
      ;;
    --tar)
      TAR_PATH="${2:?--tar requires a path}"
      DOWNLOAD=0
      shift 2
      ;;
    --force-env)
      FORCE_ENV=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      TAR_PATH="$1"
      DOWNLOAD=0
      shift
      ;;
  esac
done

# ─── Resolve image tag ────────────────────────────────────────────────────────

if [[ "$DOWNLOAD" -eq 1 && -z "$RELEASE_TGZ_URL" && -z "$TAR_PATH" ]]; then
  echo "Error: provide --url <url> or a local archive path." >&2
  echo "Run with --help for usage." >&2
  exit 1
fi

if [[ -z "$HEALTHDM_IMAGE_TAG" ]]; then
  _src="${RELEASE_TGZ_URL:-$TAR_PATH}"
  _base="$(basename "$_src")"
  _base="${_base#healthdm-prod-}"
  _base="${_base%.tar.gz}"
  _base="${_base%.tgz}"
  HEALTHDM_IMAGE_TAG="$_base"
  echo "Image tag (auto-detected): ${HEALTHDM_IMAGE_TAG}"
fi

if [[ -z "$HEALTHDM_IMAGE_TAG" ]]; then
  echo "Error: could not determine image tag. Use --tag or name your archive healthdm-prod-<tag>.tar.gz" >&2
  exit 1
fi

# ─── Create installation directory ───────────────────────────────────────────

mkdir -p "${INSTALL_DIR}"
ROOT="$(cd "${INSTALL_DIR}" && pwd)"
echo "Installation directory: ${ROOT}"
mkdir -p "${ROOT}/nginx" "${ROOT}/settings" "${ROOT}/reports"

# ─── Generate docker-compose.yml ─────────────────────────────────────────────

write_compose() {
  local root="$1"
  cat > "${root}/docker-compose.yml" <<'COMPOSE'
# Generated by healthdm-prod-setup.sh — stack for tarball-installed images.

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: healthdm-api:${TAG}
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    command: >
      sh -c "python -c 'from core.db.init_db import run; run()' &&
             uvicorn api.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./settings:/app/settings
      - ./reports:/app/reports
      - runtime_state:/app/.runtime-state
      - /etc/machine-id:/etc/machine-id:ro

  worker:
    image: healthdm-api:${TAG}
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    command: celery -A worker.app worker --loglevel=info
    volumes:
      - ./settings:/app/settings
      - ./reports:/app/reports
      - runtime_state:/app/.runtime-state
      - /etc/machine-id:/etc/machine-id:ro

  beat:
    image: healthdm-api:${TAG}
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    command: celery -A worker.app beat --loglevel=info
    volumes:
      - ./settings:/app/settings
      - runtime_state:/app/.runtime-state
      - /etc/machine-id:/etc/machine-id:ro

  frontend:
    image: healthdm-frontend:${TAG}
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "${PRODUCTION_HTTP_PORT:-8800}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend

volumes:
  postgres_data:
  runtime_state:
COMPOSE
  echo "Generated ${root}/docker-compose.yml"
}

# ─── Generate nginx/nginx.conf ────────────────────────────────────────────────

write_nginx_conf() {
  local root="$1"
  cat > "${root}/nginx/nginx.conf" <<'NGINX'
events { worker_connections 1024; }

http {
    # Docker's embedded DNS. valid=10s forces re-resolution so a rebuilt
    # container with a new IP is picked up without an nginx restart.
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;
        client_max_body_size 50m;

        location /api/ {
            set $upstream_api api:8000;
            proxy_pass http://$upstream_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            # SSE support
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header Connection '';
            chunked_transfer_encoding off;
            proxy_read_timeout 24h;
        }

        location /_next/webpack-hmr {
            set $upstream_frontend frontend:3000;
            proxy_pass http://$upstream_frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / {
            set $upstream_frontend frontend:3000;
            proxy_pass http://$upstream_frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}
NGINX
  echo "Generated ${root}/nginx/nginx.conf"
}

# ─── Generate .env ────────────────────────────────────────────────────────────

write_env() {
  local root="$1"
  local image_tag="$2"
  local http_port="${PRODUCTION_HTTP_PORT:-8800}"
  local db_pw secret salt
  db_pw="$(openssl rand -hex 24)"
  secret="$(openssl rand -hex 32)"
  salt="$(openssl rand -hex 16)"
  umask 077
  cat > "${root}/.env" <<EOF
# Auto-generated by healthdm-prod-setup.sh — do not commit
# TAG / PRODUCTION_HTTP_PORT: used by docker-compose.yml interpolation (any compose command from this dir).
TAG=${image_tag}
PRODUCTION_HTTP_PORT=${http_port}
POSTGRES_USER=healthdm
POSTGRES_PASSWORD=${db_pw}
POSTGRES_DB=healthdm
DB_HOST=postgres
DB_PORT=5432
DB_NAME=healthdm
DB_USER=healthdm
DB_PASSWORD=${db_pw}
DATABASE_URL=postgresql+asyncpg://healthdm:${db_pw}@postgres:5432/healthdm

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

SECRET_KEY=${secret}
ENCRYPTION_SALT=${salt}
SETTINGS_FILE=/app/settings/healthdm-settings.json
REPORTS_TEMPLATE_DIR=/app/reports/templates
LOG_LEVEL=INFO

XSIAM_API_URL=
XSIAM_API_KEY=
XSIAM_AUTH_ID=1

NEXT_PUBLIC_API_URL=http://localhost/api/v1
EOF
  umask 022
  echo "Generated ${root}/.env with random secrets."
}

# ─── Write all config files ───────────────────────────────────────────────────

write_compose    "${ROOT}"
write_nginx_conf "${ROOT}"

if [[ -f "${ROOT}/.env" && "${FORCE_ENV}" -eq 0 ]]; then
  echo "Keeping existing ${ROOT}/.env  (use --force-env to regenerate)"
else
  if [[ -f "${ROOT}/.env" && "${FORCE_ENV}" -eq 1 ]]; then
    echo "Regenerating .env (--force-env). If Postgres is already initialized, also run: docker compose down -v"
  fi
  write_env "${ROOT}" "${HEALTHDM_IMAGE_TAG}"
fi

# Keep TAG= in .env aligned with this run's archive (safe when preserving secrets on upgrade).
if [[ -f "${ROOT}/.env" ]]; then
  _env_new="${ROOT}/.env.tag.$$"
  grep -v '^TAG=' "${ROOT}/.env" > "${_env_new}" || true
  printf 'TAG=%s\n' "${HEALTHDM_IMAGE_TAG}" >> "${_env_new}"
  mv "${_env_new}" "${ROOT}/.env"
fi

# ─── Download or locate archive ───────────────────────────────────────────────

DEFAULT_TAR_NAME="healthdm-prod-${HEALTHDM_IMAGE_TAG}.tar.gz"

if [[ "$DOWNLOAD" -eq 1 ]]; then
  echo ""
  echo "Downloading: ${RELEASE_TGZ_URL}"
  echo "         ->  ${ROOT}/${DEFAULT_TAR_NAME}"
  curl -fL --progress-bar -o "${ROOT}/${DEFAULT_TAR_NAME}" "${RELEASE_TGZ_URL}"
  TAR_PATH="${ROOT}/${DEFAULT_TAR_NAME}"
fi

if [[ -z "${TAR_PATH}" ]]; then
  if [[ -f "${ROOT}/${DEFAULT_TAR_NAME}" ]]; then
    TAR_PATH="${ROOT}/${DEFAULT_TAR_NAME}"
  else
    echo "No archive found. Pass a path or use --url." >&2
    exit 1
  fi
fi

# Resolve to absolute path
if [[ "${TAR_PATH}" != /* ]]; then
  TAR_PATH="$(cd "$(dirname "${TAR_PATH}")" && pwd)/$(basename "${TAR_PATH}")"
fi

[[ -f "${TAR_PATH}" ]] || { echo "File not found: ${TAR_PATH}" >&2; exit 1; }

# ─── Load Docker images ───────────────────────────────────────────────────────

echo ""
echo "Loading Docker images from: ${TAR_PATH}"
case "${TAR_PATH}" in
  *.tar.gz|*.tgz) gunzip -c "${TAR_PATH}" | docker load ;;
  *.tar)          docker load -i "${TAR_PATH}" ;;
  *)              echo "Expected .tar.gz, .tgz, or .tar — got: ${TAR_PATH}" >&2; exit 1 ;;
esac

# ─── Start stack ──────────────────────────────────────────────────────────────

echo ""
echo "Starting stack (TAG=${HEALTHDM_IMAGE_TAG})..."
cd "${ROOT}"
TAG="${HEALTHDM_IMAGE_TAG}" docker compose up -d

echo ""
echo "Done."
echo "  App:      http://localhost:${PRODUCTION_HTTP_PORT:-8800}"
echo "  Stop:     cd ${ROOT} && docker compose down"
echo "  Logs:     cd ${ROOT} && docker compose logs -f"
